# Generated by Django 4.2.1 on 2023-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.FileField(upload_to='static\\uploads'),
        ),
    ]
